"""Shared parsing helpers for every NIST OSCAL *catalog* ingester.

NIST publishes SP 800-53 Rev 5, CSF 2.0, and SP 800-171 Rev 3 as OSCAL
catalogs sharing the same recursive `catalog.groups[].controls[]` JSON shape
(a top-level grouping — family/function — containing nested "control" nodes,
themselves arbitrarily nestable: 800-53 nests *enhancements* this way, CSF
nests *subcategories* under *categories* this way). That structural overlap
is deliberate on NIST's part (all three are generated by the same OSCAL
toolchain) and is what lets `nist_sp800_53.py`, `nist_csf.py`, and
`nist_sp800_171.py` all share this one parsing module instead of
duplicating ~150 lines of traversal/label-resolution/statement-flattening
logic three times.

Each framework-specific ingester still owns its own `parse_catalog()`: what
counts as a "control" worth emitting, what its `control_family` is, and
which `Framework`/version to stamp it with differ enough (see each module's
docstring) that a single shared `parse_catalog()` would need more
per-framework branching than it's worth.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import requests
import structlog

logger = structlog.get_logger(__name__)

_PARAM_PLACEHOLDER = re.compile(r"\{\{\s*insert:\s*param,\s*([\w.-]+)\s*\}\}")


def fetch_catalog(source: str, *, timeout: float = 30.0) -> dict[str, Any]:
    """Load an OSCAL catalog JSON document from a local file path or an HTTP(S) URL."""
    if source.startswith(("http://", "https://")):
        logger.info("fetching_oscal_catalog", source=source)
        response = requests.get(source, timeout=timeout)
        response.raise_for_status()
        return dict(response.json())

    path = Path(source)
    logger.info("reading_oscal_catalog", source=str(path))
    with path.open("r", encoding="utf-8") as f:
        return dict(json.load(f))


def canonical_label(props: list[dict[str, Any]], fallback: str) -> str:
    for prop in props:
        if prop.get("name") == "label" and "class" not in prop:
            value = prop.get("value")
            if isinstance(value, str):
                return value
    return fallback


def guess_canonical_id(raw_id: str) -> str:
    """Best-effort canonicalization for a raw OSCAL id with no resolvable label.

    'ac-2' -> 'AC-2', 'ac-2.1' -> 'AC-2(1)'. Only used as a fallback when a
    referenced control's real label can't be found in the catalog.
    """
    prefix, _, rest = raw_id.partition("-")
    if not rest:
        return raw_id.upper()
    base, _, enhancement = rest.partition(".")
    if enhancement:
        return f"{prefix.upper()}-{base}({enhancement})"
    return f"{prefix.upper()}-{base}"


def is_withdrawn(control: dict[str, Any]) -> bool:
    return any(
        prop.get("name") == "status" and prop.get("value") == "withdrawn"
        for prop in control.get("props", [])
    )


def iter_controls_recursive(
    controls: list[dict[str, Any]], parent_raw_id: str | None = None
) -> Iterator[tuple[dict[str, Any], str | None]]:
    """Yield every (control, parent_raw_id) pair, descending into nested `controls`."""
    for control in controls:
        yield control, parent_raw_id
        nested = control.get("controls")
        if nested:
            yield from iter_controls_recursive(nested, parent_raw_id=control["id"])


def build_label_index(groups: list[dict[str, Any]]) -> dict[str, str]:
    """Map every control's raw OSCAL id to its canonical display label."""
    index: dict[str, str] = {}
    for group in groups:
        for control, _parent in iter_controls_recursive(group.get("controls", [])):
            index[control["id"]] = canonical_label(control.get("props", []), control["id"])
    return index


def resolve_href_ids(
    control: dict[str, Any], rel: str, label_index: dict[str, str], self_raw_id: str
) -> list[str]:
    """Resolve every link with the given `rel` to its target's canonical label.

    `href` is usually a `#<raw-id>` fragment (800-53's convention), but CSF
    2.0's OSCAL catalog uses bare raw-id hrefs with no leading `#` for its
    `incorporated_into` links — both forms are accepted here rather than
    forking this function per framework.
    """
    resolved: dict[str, None] = {}
    for link in control.get("links", []):
        if link.get("rel") != rel:
            continue
        href = link.get("href", "")
        if not href:
            continue
        raw_ref = href[1:] if href.startswith("#") else href
        if raw_ref == self_raw_id:
            continue
        label = label_index.get(raw_ref) or guess_canonical_id(raw_ref)
        resolved.setdefault(label, None)
    return list(resolved.keys())


def param_display(param: dict[str, Any]) -> str:
    if isinstance(param.get("label"), str):
        return param["label"]
    select = param.get("select")
    if select and select.get("choice"):
        return "one of: " + ", ".join(select["choice"])
    return str(param.get("id", ""))


def resolve_param_placeholders(text: str, params_by_id: dict[str, str]) -> str:
    def _sub(match: re.Match[str]) -> str:
        label = params_by_id.get(match.group(1))
        return f"[{label}]" if label else match.group(0)

    return _PARAM_PLACEHOLDER.sub(_sub, text)


def flatten_statement_parts(
    parts: list[dict[str, Any]], params_by_id: dict[str, str], depth: int = 0
) -> list[str]:
    lines: list[str] = []
    for part in parts:
        label = next((p["value"] for p in part.get("props", []) if p.get("name") == "label"), "")
        prose = part.get("prose")
        if prose:
            resolved = resolve_param_placeholders(prose, params_by_id)
            prefix = f"{label} " if label else ""
            lines.append(("  " * depth) + f"{prefix}{resolved}")
        if part.get("parts"):
            lines.extend(flatten_statement_parts(part["parts"], params_by_id, depth + 1))
    return lines


def extract_statement(control: dict[str, Any], params_by_id: dict[str, str]) -> str:
    statement_part = next(
        (p for p in control.get("parts", []) if p.get("name") == "statement"), None
    )
    if statement_part is None:
        return ""
    lines: list[str] = []
    if statement_part.get("prose"):
        lines.append(resolve_param_placeholders(statement_part["prose"], params_by_id))
    lines.extend(flatten_statement_parts(statement_part.get("parts", []), params_by_id))
    return "\n".join(lines)


def group_label(group: dict[str, Any]) -> str:
    return next(
        (p["value"] for p in group.get("props", []) if p.get("name") == "label"),
        group["id"].upper(),
    )
